export enum MedicalSpecialties {
  Alergologia = "Alergologia",
  Anestesiologia = "Anestesiologia",
  Angiologia = "Angiologia",
  Cardiologia = "Cardiologia",
  CirurgiaGeral = "Cirurgia Geral",
  CirurgiaCardiaca = "Cirurgia Cardíaca",
  CirurgiaPlastica = "Cirurgia Plástica",
  CirurgiaVascular = "Cirurgia Vascular",
  ClinicaMedica = "Clínica Médica",
  Dermatologia = "Dermatologia",
  Endocrinologia = "Endocrinologia",
  Endoscopia = "Endoscopia",
  Gastroenterologia = "Gastroenterologia",
  Geriatria = "Geriatria",
  GinecologiaObstetricia = "Ginecologia e Obstetrícia",
  Hematologia = "Hematologia",
  Homeopatia = "Homeopatia",
  Infectologia = "Infectologia",
  Mastologia = "Mastologia",
  MedicinaDoEsporte = "Medicina do Esporte",
  MedicinaDoTrabalho = "Medicina do Trabalho",
  MedicinaDeFamilia = "Medicina de Família e Comunidade",
  MedicinaLegal = "Medicina Legal",
  MedicinaNuclear = "Medicina Nuclear",
  MedicinaPreventiva = "Medicina Preventiva",
  Nefrologia = "Nefrologia",
  Neurocirurgia = "Neurocirurgia",
  Neurologia = "Neurologia",
  Nutrologia = "Nutrologia",
  Oftalmologia = "Oftalmologia",
  Oncologia = "Oncologia",
  Ortopedia = "Ortopedia e Traumatologia",
  Otorrinolaringologia = "Otorrinolaringologia",
  Patologia = "Patologia",
  Pediatria = "Pediatria",
  Pneumologia = "Pneumologia",
  Psiquiatria = "Psiquiatria",
  Radiologia = "Radiologia e Diagnóstico por Imagem",
  Reumatologia = "Reumatologia",
  Urologia = "Urologia",
}
export const medicalSpecialties = Object.entries(MedicalSpecialties).map(
  ([key, value]) => ({
    value: MedicalSpecialties[key as keyof typeof MedicalSpecialties],
    label: value,
  }),
);
